CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT UNIQUE NOT NULL, password_hash TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sessions (token_hash TEXT PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, expires_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS sessions_expiry ON sessions(expires_at);
CREATE TABLE IF NOT EXISTS topic_progress (user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, topic_id INTEGER NOT NULL, status TEXT NOT NULL CHECK(status IN ('NotStarted','InProgress','Mastered','NeedsReview')), last_reviewed TEXT, PRIMARY KEY(user_id,topic_id));
CREATE TABLE IF NOT EXISTS exam_settings (user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE, exam_date TEXT NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS auth_limits (key TEXT PRIMARY KEY, window INTEGER NOT NULL, hits INTEGER NOT NULL);
